#spring.datasourcer.url=jdbc:mysql://localhost/forumhub_db
#spring.datasourcer.username=
#spring.datasourcer.password=
#spring.datasourcer.drive_classe_name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update